export enum CHANNEL_EVENT_TYPE {
    BAN = "BANNED",
    UNBAN = "UNBANED",
    MUTE = "MUTED",
    UNMUTE = "UNMUTE",
    KICK = "KICKED",
    UPGRADE = "UPGRADED",
    DOWNGRADE = "DOWNGRADED",
    CHANNEL_EDIT = "CHANNEL EDITED",
    BLOCKED = "BLOCKED",
    UNBLOCKED = "UNBLOCKED"
  }